server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_templates?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
